-- MySQL Script generated by MySQL Workbench
-- Вт 09 ноя 2021 21:30:30
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema wishes
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema wishes
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `wishes` ;
USE `wishes` ;

-- -----------------------------------------------------
-- Table `wishes`.`usr`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wishes`.`usr` (
  `uid` VARCHAR(9) NOT NULL,
  `user_lang` VARCHAR(10) NULL,
  `authkey` VARCHAR(100) NULL,
  UNIQUE INDEX `uid_UNIQUE` (`uid` ASC) VISIBLE,
  PRIMARY KEY (`uid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wishes`.`100`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wishes`.`100` (
  `uid` VARCHAR(9) NOT NULL,
  `time` DATETIME NOT NULL,
  `name` VARCHAR(30) NOT NULL,
  `item_type` VARCHAR(15) NOT NULL,
  `rank_type` INT(1) UNSIGNED NOT NULL,
  `id` VARCHAR(19) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `uid_idx` (`uid` ASC) VISIBLE,
  CONSTRAINT `forq`
    FOREIGN KEY (`uid`)
    REFERENCES `wishes`.`usr` (`uid`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wishes`.`200`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wishes`.`200` (
  `uid` VARCHAR(9) NOT NULL,
  `time` DATETIME NOT NULL,
  `name` VARCHAR(30) NOT NULL,
  `item_type` VARCHAR(15) NOT NULL,
  `rank_type` INT(1) UNSIGNED NOT NULL,
  `id` VARCHAR(19) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `uid_idx` (`uid` ASC) VISIBLE,
  CONSTRAINT `forw`
    FOREIGN KEY (`uid`)
    REFERENCES `wishes`.`usr` (`uid`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wishes`.`301`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wishes`.`301` (
  `uid` VARCHAR(9) NOT NULL,
  `time` DATETIME NOT NULL,
  `name` VARCHAR(30) NOT NULL,
  `item_type` VARCHAR(15) NOT NULL,
  `rank_type` INT(1) UNSIGNED NOT NULL,
  `id` VARCHAR(19) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `uid_idx` (`uid` ASC) VISIBLE,
  CONSTRAINT `forr`
    FOREIGN KEY (`uid`)
    REFERENCES `wishes`.`usr` (`uid`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wishes`.`302`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wishes`.`302` (
  `uid` VARCHAR(9) NOT NULL,
  `time` DATETIME NOT NULL,
  `name` VARCHAR(30) NOT NULL,
  `item_type` VARCHAR(15) NOT NULL,
  `rank_type` INT(1) UNSIGNED NOT NULL,
  `id` VARCHAR(19) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `uid_idx` (`uid` ASC) VISIBLE,
  CONSTRAINT `fore`
    FOREIGN KEY (`uid`)
    REFERENCES `wishes`.`usr` (`uid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
